#ifndef _EXCEPTION_LIST_H
#define _EXCEPTION_LIST_H


#define EXCEPTION_COUNT             20
#define IDT_SIZE                    256

void DIVIDE_ZERO_HANDLER ();
void DEBUG_HANDLER  ();
void NON_MASKABLE_HANDLER  ();
void BREAKPOINT_HANDLER  ();
void OVERFLOW_HANDLER  ();
void RANGE_EXCEEDED_HANDLER  ();
void INVALID_OP_HANDLER  ();
void DEVICE_UNALIBLE_HANDLER  ();
void DOUBLE_FAULT_HANDLER  ();
void COPROCESSOR_OVERRUN_HANDLER  ();
void INVALID_TSS_HANDLER  ();
void SEGMENT_NOT_PRESENT_HANDLER  ();
void STACK_FAULT_HANDLER  ();
void GENRAL_PROTECTION_HANDLER  ();
void PAGE_FAULT_HANDLER  ();
void RESERVED_HANDLER  ();
void X87_FLOATING_POINT_HANDLER  ();
void ALIGHMENT_CHECK_HANDLER  ();
void MACHINE_CHECK_HANDLER  ();
void SIMD_FLOATING_POINT_HANDLER  (); 

#endif 
