boot.o: boot.S include/boot/multiboot.h include/boot/x86_desc.h \
  include/types.h
handler.o: kernel/handler.S
x86_desc.o: kernel/x86_desc.S include/boot/x86_desc.h include/types.h
fs.o: drivers/fs.c include/drivers/fs.h include/types.h include/lib.h \
  include/io.h
keyboard.o: drivers/keyboard.c include/drivers/keyboard.h include/types.h \
  include/drivers/terminal.h include/boot/i8259.h include/lib.h \
  include/io.h
rtc.o: drivers/rtc.c include/drivers/rtc.h include/types.h \
  include/boot/i8259.h include/lib.h include/io.h
terminal.o: drivers/terminal.c include/drivers/terminal.h \
  include/drivers/keyboard.h include/types.h include/lib.h include/io.h
ece391_vfs.o: kernel/ece391_vfs.c include/vfs/ece391_vfs.h \
  include/vfs/file.h include/types.h include/drivers/fs.h \
  include/drivers/terminal.h include/drivers/keyboard.h \
  include/drivers/rtc.h include/lib.h include/io.h
exception.o: kernel/exception.c include/boot/exception.h include/io.h \
  include/types.h
file.o: kernel/file.c include/vfs/file.h include/types.h \
  include/drivers/fs.h include/vfs/ece391_vfs.h include/lib.h \
  include/io.h
i8259.o: kernel/i8259.c include/boot/i8259.h include/types.h \
  include/lib.h
idt.o: kernel/idt.c include/types.h include/boot/idt.h \
  include/boot/x86_desc.h include/boot/exception.h \
  include/boot/interrupt.h include/boot/syscall.h include/lib.h \
  include/io.h
kernel.o: kernel/kernel.c include/boot/multiboot.h include/types.h \
  include/boot/x86_desc.h include/boot/page.h include/boot/idt.h \
  include/boot/i8259.h include/drivers/keyboard.h \
  include/drivers/terminal.h include/drivers/rtc.h include/drivers/fs.h \
  include/vfs/ece391_vfs.h include/vfs/file.h include/debug.h \
  include/lib.h include/io.h include/tests/tests.h
page.o: kernel/page.c include/boot/x86_desc.h include/types.h \
  include/boot/page.h include/lib.h
syscall.o: kernel/syscall.c include/boot/syscall.h include/io.h \
  include/types.h
vfs.o: kernel/vfs.c
io.o: lib/io.c include/io.h include/types.h include/lib.h
lib.o: lib/lib.c include/lib.h include/types.h
tests.o: tests/tests.c include/boot/x86_desc.h include/types.h \
  include/lib.h include/io.h include/drivers/terminal.h \
  include/drivers/keyboard.h include/drivers/rtc.h include/tests/tests.h \
  include/vfs/ece391_vfs.h include/vfs/file.h include/drivers/fs.h
